CREATE DATABASE testDB;
IF NOT EXISTS(SELECT * FROM sys.databases WHERE name = 'HMTS2')
  BEGIN
    CREATE DATABASE [HMTS2]
  END
GO
USE [HMTS2]
GO

SELECT 
	'ALTER TABLE ' +  OBJECT_SCHEMA_NAME(k.parent_object_id) +
	'.[' + OBJECT_NAME(k.parent_object_id) + 
	'] DROP CONSTRAINT ' + k.name
	FROM sys.foreign_keys k
	WHERE referenced_object_id = object_id('TB_XRF_SEQ_TEMP');

IF EXISTS(SELECT * FROM sys.tables WHERE SCHEMA_NAME(schema_id) LIKE 'dbo' AND name like 'TB_XRF_SEQ_TEMP')  
   DROP TABLE [dbo].[TB_XRF_SEQ_TEMP];

CREATE TABLE TB_XRF_SEQ_TEMP
(
  SMPLNO      VARCHAR(12)                 NOT NULL,
  TMBDIV      VARCHAR(1)                  NOT NULL,
  ORDSEQ      DECIMAL(3),
  MTCHECK     VARCHAR(2),
  RECHECK     VARCHAR(1),
  SUJI        VARCHAR(2),
  SMPLLENGTH  DECIMAL(10),
  EXNAME      VARCHAR(50)
)

ALTER TABLE TB_XRF_SEQ_TEMP ADD CONSTRAINT PK_TB_XRF_SEQ_TEMP
	PRIMARY KEY  (SMPLNO, TMBDIV)

SELECT 
'ALTER TABLE ' +  OBJECT_SCHEMA_NAME(k.parent_object_id) +
'.[' + OBJECT_NAME(k.parent_object_id) + 
'] DROP CONSTRAINT ' + k.name
FROM sys.foreign_keys k
WHERE referenced_object_id = object_id('TB_XRF_AUTO_HISTORY')

IF EXISTS(SELECT * FROM sys.tables WHERE SCHEMA_NAME(schema_id) LIKE 'dbo' AND name like 'TB_XRF_AUTO_HISTORY')  
   DROP TABLE [dbo].[TB_XRF_AUTO_HISTORY];

CREATE TABLE TB_XRF_AUTO_HISTORY
(
  XRFHSEQ        DECIMAL(8)                      NOT NULL,
  SMPLNO         VARCHAR(12)              NOT NULL,
  TMBDIV         VARCHAR(1)               NOT NULL,
  ELEMENTNAME    VARCHAR(50),
  ELEMENTVALUE   DECIMAL(5,1),
  FBDIV          VARCHAR(1),
  WCDDIV         VARCHAR(1),
  XRFDATE        DATE,
  EXNAME         VARCHAR(50),
  RESOURCEVALUE  DECIMAL(5,1)
)


ALTER TABLE TB_XRF_AUTO_HISTORY ADD CONSTRAINT PK_TB_XRF_AUTO_HISTORY2PRIMARY
	PRIMARY KEY (XRFHSEQ)


SELECT
	'ALTER TABLE ' +  OBJECT_SCHEMA_NAME(k.parent_object_id) +
	'.[' + OBJECT_NAME(k.parent_object_id) + 
	'] DROP CONSTRAINT ' + k.name
	FROM sys.foreign_keys k
	WHERE referenced_object_id = object_id('TB_XRF_FA_DIRECT');

IF EXISTS(SELECT * FROM sys.tables WHERE SCHEMA_NAME(schema_id) LIKE 'dbo' AND name like 'TB_XRF_FA_DIRECT')  
   DROP TABLE [dbo].[TB_XRF_FA_DIRECT];

CREATE TABLE TB_XRF_FA_DIRECT
(
  SMPLNO          VARCHAR(8)              NOT NULL,
  TMBDIV          VARCHAR(1)              NOT NULL,
  CARVENUMBER     VARCHAR(1)              NOT NULL,
  SMPLLENGTH      DECIMAL(4)                     NOT NULL,
  SUJI            VARCHAR(2),
  PROCESSDIV      VARCHAR(1),
  LOADER          VARCHAR(1),
  LOADER_DATE     DATE,
  PRCMOVE         VARCHAR(1),
  PRCMOVE_DATE    DATE,
  PRESS           VARCHAR(1),
  PRESS_DATE      DATE,
  CARVE           VARCHAR(1),
  CARVE_DATE      DATE,
  CLEAN           VARCHAR(1),
  CLEAN_DATE      DATE,
  DISCHARGE       VARCHAR(1),
  DISCHARGE_DATE  DATE,
  BUFFER          VARCHAR(1),
  BUFFER_DATE     DATE,
  XRF             VARCHAR(1),
  XRF_DATE        DATE,
  COMPLETE_DATE   DATE,
  FA_DIRECRT_SEQ  DECIMAL(10)                    DEFAULT 1
)


ALTER TABLE TB_XRF_FA_DIRECT ADD CONSTRAINT TB_XRF_FA_DIRECT_PK PRIMARY KEY
  (SMPLNO, TMBDIV, CARVENUMBER);

SELECT
	'ALTER TABLE ' +  OBJECT_SCHEMA_NAME(k.parent_object_id) +
	'.[' + OBJECT_NAME(k.parent_object_id) + 
	'] DROP CONSTRAINT ' + k.name
	FROM sys.foreign_keys k
	WHERE referenced_object_id = object_id('TB_XRF_HISTORY')

IF EXISTS(SELECT * FROM sys.tables WHERE SCHEMA_NAME(schema_id) LIKE 'dbo' AND name like 'TB_XRF_HISTORY')  
   DROP TABLE [dbo].[TB_XRF_HISTORY];

CREATE TABLE TB_XRF_HISTORY
(
  XRFHSEQ     DECIMAL(8)                         NOT NULL,
  SMPLNO      VARCHAR(12)                 NOT NULL,
  TMBDIV      VARCHAR(1)                  NOT NULL,
  SMPLLENGTH  DECIMAL(10),
  XRFFRONTW   DECIMAL(4,1),
  XRFFRONTC   DECIMAL(4,1),
  XRFFRONTD   DECIMAL(4,1),
  XRFFRONTA   DECIMAL(4,1),
  XRFBACKW    DECIMAL(4,1),
  XRFBACKC    DECIMAL(4,1),
  XRFBACKD    DECIMAL(4,1),
  XRFBACKA    DECIMAL(4,1),
  CRFRONTW    DECIMAL(4),
  CRFRONTC    DECIMAL(4),
  CRFRONTD    DECIMAL(4),
  CRFRONTA    DECIMAL(4),
  CRBACKW     DECIMAL(4),
  CRBACKC     DECIMAL(4),
  CRBACKD     DECIMAL(4),
  CRBACKA     DECIMAL(4),
  SIFRONTW    DECIMAL(4),
  SIFRONTC    DECIMAL(4),
  SIFRONTD    DECIMAL(4),
  SIFRONTA    DECIMAL(4),
  SIBACKW     DECIMAL(4),
  SIBACKC     DECIMAL(4),
  SIBACKD     DECIMAL(4),
  SIBACKA     DECIMAL(4),
  RSNFRONTW   DECIMAL(4),
  RSNFRONTC   DECIMAL(4),
  RSNFRONTD   DECIMAL(4),
  RSNFRONTA   DECIMAL(4),
  RSNBACKW    DECIMAL(4),
  RSNBACKC    DECIMAL(4),
  RSNBACKD    DECIMAL(4),
  RSNBACKA    DECIMAL(4),
  EXT1FRONTW  DECIMAL(4),
  EXT1FRONTC  DECIMAL(4),
  EXT1FRONTD  DECIMAL(4),
  EXT1FRONTA  DECIMAL(4),
  EXT1BACKW   DECIMAL(4),
  EXT1BACKC   DECIMAL(4),
  EXT1BACKD   DECIMAL(4),
  EXT1BACKA   DECIMAL(4),
  EXT2FRONTW  DECIMAL(4),
  EXT2FRONTC  DECIMAL(4),
  EXT2FRONTD  DECIMAL(4),
  EXT2FRONTA  DECIMAL(4),
  EXT2BACKW   DECIMAL(4),
  EXT2BACKC   DECIMAL(4),
  EXT2BACKD   DECIMAL(4),
  EXT2BACKA   DECIMAL(4),
  FEFRONTW    DECIMAL(3,1),
  FEFRONTC    DECIMAL(3,1),
  FEFRONTD    DECIMAL(3,1),
  FEFRONTA    DECIMAL(3,1),
  FEBACKW     DECIMAL(3,1),
  FEBACKC     DECIMAL(3,1),
  FEBACKD     DECIMAL(3,1),
  FEBACKA     DECIMAL(3,1),
  SUJIGUBUN   VARCHAR(2),
  XRFAMOUNT   DECIMAL(4,1),
  XRFDATE     DATE
)

ALTER TABLE TB_XRF_HISTORY ADD CONSTRAINT PK_TB_XRF_HISTORY2 PRIMARY KEY (XRFHSEQ)





